import {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clock,
  CloudOff,
  Copy,
  Delete,
  Eye,
  EyeOff,
  Flame,
  Headphones,
  House,
  Info,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MicOff,
  Minus,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Play,
  RefreshCw,
  RotateCcw,
  Search,
  Shield,
  Smartphone,
  Sparkles,
  StickyNote,
  Tag,
  Target,
  ThumbsDown,
  ThumbsUp,
  TrendingUp,
  User,
  Users,
  WifiOff,
  X,
  type LucideIcon,
} from "lucide-react";

/** The same icon set (and the same names) as the phone app. */
const icons = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  bell: Bell,
  "calendar-clock": CalendarClock,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  alert: CircleAlert,
  "check-circle": CircleCheck,
  clock: Clock,
  "cloud-off": CloudOff,
  copy: Copy,
  backspace: Delete,
  eye: Eye,
  "eye-off": EyeOff,
  flame: Flame,
  headphones: Headphones,
  home: House,
  info: Info,
  "list-checks": ListChecks,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  pin: MapPin,
  "mic-off": MicOff,
  minus: Minus,
  phone: Phone,
  "phone-call": PhoneCall,
  "phone-forward": PhoneForwarded,
  "phone-in": PhoneIncoming,
  "phone-missed": PhoneMissed,
  "phone-off": PhoneOff,
  "phone-out": PhoneOutgoing,
  play: Play,
  refresh: RefreshCw,
  history: RotateCcw,
  search: Search,
  shield: Shield,
  smartphone: Smartphone,
  sparkles: Sparkles,
  note: StickyNote,
  tag: Tag,
  target: Target,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  trending: TrendingUp,
  user: User,
  users: Users,
  "wifi-off": WifiOff,
  x: X,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  className?: string;
}

export function Icon({ name, size = 22, color = "currentColor", strokeWidth = 2.2, className }: IconProps) {
  const Glyph = icons[name];
  return <Glyph size={size} color={color} strokeWidth={strokeWidth} className={className} aria-hidden="true" focusable="false" />;
}
