import React from 'react';
import {
  AppWindow,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  BatteryCharging,
  Bell,
  BellRing,
  Bluetooth,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDot,
  Clock,
  Cloud,
  CloudOff,
  Contact,
  Delete,
  Eye,
  EyeOff,
  Flame,
  Grip,
  Headphones,
  House,
  Info,
  ListChecks,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  MapPin,
  Mic,
  MicOff,
  Minus,
  NotebookPen,
  Pause,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PictureInPicture2,
  Play,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  Search,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  StickyNote,
  Tag,
  Target,
  TrendingUp,
  Trophy,
  Upload,
  User,
  Users,
  Volume2,
  Wifi,
  WifiOff,
  X,
  Zap,
} from 'lucide-react-native';

const icons = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  bell: Bell,
  'calendar-clock': CalendarClock,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  alert: CircleAlert,
  'check-circle': CircleCheck,
  clock: Clock,
  cloud: Cloud,
  'cloud-off': CloudOff,
  contact: Contact,
  backspace: Delete,
  eye: Eye,
  'eye-off': EyeOff,
  flame: Flame,
  headphones: Headphones,
  home: House,
  info: Info,
  'list-checks': ListChecks,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  pin: MapPin,
  mic: Mic,
  'mic-off': MicOff,
  minus: Minus,
  pause: Pause,
  phone: Phone,
  'phone-call': PhoneCall,
  'phone-forward': PhoneForwarded,
  'phone-in': PhoneIncoming,
  'phone-missed': PhoneMissed,
  'phone-off': PhoneOff,
  'phone-out': PhoneOutgoing,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  history: RotateCcw,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  smartphone: Smartphone,
  sparkles: Sparkles,
  note: StickyNote,
  tag: Tag,
  target: Target,
  trending: TrendingUp,
  trophy: Trophy,
  upload: Upload,
  user: User,
  users: Users,
  volume: Volume2,
  wifi: Wifi,
  'wifi-off': WifiOff,
  x: X,
  zap: Zap,
  'app-window': AppWindow,
  battery: BatteryCharging,
  'bell-ring': BellRing,
  bluetooth: Bluetooth,
  'chevron-down': ChevronDown,
  rec: CircleDot,
  keypad: Grip,
  'lock-keyhole': LockKeyhole,
  'note-pen': NotebookPen,
  bubble: PictureInPicture2,
  rocket: Rocket,
  'shield-check': ShieldCheck,
} as const;

export type IconName = keyof typeof icons;

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 22, color = '#1C1C1C', strokeWidth = 2.2 }: IconProps) {
  const Glyph = icons[name];
  return <Glyph size={size} color={color} strokeWidth={strokeWidth} />;
}
