"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 02:52:02.921793
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_dispositions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('requires_callback', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_dispositions')),
    sa.UniqueConstraint('code', name=op.f('uq_call_dispositions_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('teams',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('employees',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_target', sa.Integer(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('device_binding_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('password_changed_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_employees_role_id_roles')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_employees_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('email', name=op.f('uq_employees_email')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_employees_employee_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('ix_employees_team_active', ['team_id', 'is_active'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], name=op.f('fk_audit_logs_actor_id_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('target_calls', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], name=op.f('fk_campaigns_created_by_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('name', name=op.f('uq_campaigns_name')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_status', ['status'], unique=False)

    op.create_table('employee_devices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_uid', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_devices_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_devices')),
    sa.UniqueConstraint('employee_id', 'device_uid', name='uq_employee_devices_employee_device'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('data', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('read_at', app.core.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_notifications_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_employee_read_created', ['employee_id', 'is_read', 'created_at'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['employees.id'], name=op.f('fk_settings_updated_by_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('campaign_assignees',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('employee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('added_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_assignees_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_campaign_assignees_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_assignees')),
    sa.UniqueConstraint('campaign_id', 'employee_id', name='uq_campaign_assignees_campaign_employee'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('employee_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_refresh_hash', sa.String(length=64), nullable=True),
    sa.Column('prev_valid_until', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('last_used_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['employee_devices.id'], name=op.f('fk_employee_sessions_device_id_employee_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_sessions_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_sessions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('employee_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_employee_sessions_employee_revoked', ['employee_id', 'revoked_at'], unique=False)

    op.create_table('imports',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('options', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('campaign_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('updated_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('assigned_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('confirmed_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_imports_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], name=op.f('fk_imports_created_by_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imports')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.create_index('ix_imports_created_by_created', ['created_by', 'created_at'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_raw', sa.String(length=64), nullable=False),
    sa.Column('normalized_phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('tags', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('custom_fields', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('import_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_called_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('last_disposition_code', sa.String(length=32), nullable=True),
    sa.Column('next_eligible_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('deleted_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], name=op.f('fk_contacts_created_by_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk_contacts_import_id_imports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('normalized_phone', name='uq_contacts_normalized_phone'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('ix_contacts_category', ['category'], unique=False)
        batch_op.create_index('ix_contacts_next_eligible_at', ['next_eligible_at'], unique=False)
        batch_op.create_index('ix_contacts_status', ['status'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('client_call_id', sa.String(length=64), nullable=False),
    sa.Column('external_call_reference', sa.String(length=128), nullable=True),
    sa.Column('phone_number_snapshot', sa.String(length=32), nullable=False),
    sa.Column('contact_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('answered_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('ended_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('disposition_id', sa.Integer(), nullable=True),
    sa.Column('disposition_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('device_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_calls_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_calls_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['employee_devices.id'], name=op.f('fk_calls_device_id_employee_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disposition_id'], ['call_dispositions.id'], name=op.f('fk_calls_disposition_id_call_dispositions')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_calls_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls')),
    sa.UniqueConstraint('employee_id', 'client_call_id', name='uq_calls_employee_client_call'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index('ix_calls_campaign_started', ['campaign_id', 'started_at'], unique=False)
        batch_op.create_index('ix_calls_contact_started', ['contact_id', 'started_at'], unique=False)
        batch_op.create_index('ix_calls_employee_started', ['employee_id', 'started_at'], unique=False)
        batch_op.create_index('ix_calls_status_started', ['status', 'started_at'], unique=False)

    op.create_table('campaign_contacts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('added_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_contacts_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_campaign_contacts_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_contacts')),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_contacts_campaign_contact'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('campaign_contacts', schema=None) as batch_op:
        batch_op.create_index('ix_campaign_contacts_campaign_status', ['campaign_id', 'status'], unique=False)
        batch_op.create_index('ix_campaign_contacts_contact', ['contact_id'], unique=False)

    op.create_table('contact_assignments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('employee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('campaign_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('active_contact_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('assigned_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('released_at', app.core.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['employees.id'], name=op.f('fk_contact_assignments_assigned_by_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_contact_assignments_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_assignments_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_contact_assignments_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_assignments')),
    sa.UniqueConstraint('active_contact_id', name='uq_contact_assignments_active_contact'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('contact_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_contact_assignments_campaign', ['campaign_id'], unique=False)
        batch_op.create_index('ix_contact_assignments_contact', ['contact_id'], unique=False)
        batch_op.create_index('ix_contact_assignments_employee_status', ['employee_id', 'status'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duplicate_of', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('normalized_phone', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('errors', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_import_rows_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk_import_rows_import_id_imports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index('ix_import_rows_import_row', ['import_id', 'row_number'], unique=False)
        batch_op.create_index('ix_import_rows_import_status', ['import_id', 'status'], unique=False)

    op.create_table('call_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('payload', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_events_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_events')),
    sa.UniqueConstraint('call_id', 'event_type', 'occurred_at', name='uq_call_events_call_type_time'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.create_index('ix_call_events_call_time', ['call_id', 'occurred_at'], unique=False)

    op.create_table('call_notes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('author_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], name=op.f('fk_call_notes_author_id_employees')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_notes_call_id_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_call_notes_contact_id_contacts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_notes')),
    sa.UniqueConstraint('author_id', 'client_ref', name='uq_call_notes_author_client_ref'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('call_notes', schema=None) as batch_op:
        batch_op.create_index('ix_call_notes_call', ['call_id'], unique=False)
        batch_op.create_index('ix_call_notes_contact_created', ['contact_id', 'created_at'], unique=False)

    op.create_table('callbacks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('call_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('scheduled_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('completed_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_callbacks_call_id_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_callbacks_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_callbacks_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callbacks')),
    sa.UniqueConstraint('employee_id', 'client_ref', name='uq_callbacks_employee_client_ref'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('callbacks', schema=None) as batch_op:
        batch_op.create_index('ix_callbacks_contact', ['contact_id'], unique=False)
        batch_op.create_index('ix_callbacks_employee_scheduled_status', ['employee_id', 'scheduled_at', 'status'], unique=False)

    op.create_table('recordings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('employee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('declared_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('upload_status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('uploaded_at', app.core.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_recordings_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_recordings_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings')),
    sa.UniqueConstraint('call_id', name='uq_recordings_call'),
    sa.UniqueConstraint('uid', name='uq_recordings_uid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_index('ix_recordings_employee_created', ['employee_id', 'created_at'], unique=False)

    op.create_table('recording_access_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('recording_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], name=op.f('fk_recording_access_logs_actor_id_employees')),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_recording_access_logs_recording_id_recordings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recording_access_logs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('recording_access_logs', schema=None) as batch_op:
        batch_op.create_index('ix_recording_access_logs_recording_created', ['recording_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording_access_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_recording_access_logs_recording_created')

    op.drop_table('recording_access_logs')
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_index('ix_recordings_employee_created')

    op.drop_table('recordings')
    with op.batch_alter_table('callbacks', schema=None) as batch_op:
        batch_op.drop_index('ix_callbacks_employee_scheduled_status')
        batch_op.drop_index('ix_callbacks_contact')

    op.drop_table('callbacks')
    with op.batch_alter_table('call_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_call_notes_contact_created')
        batch_op.drop_index('ix_call_notes_call')

    op.drop_table('call_notes')
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.drop_index('ix_call_events_call_time')

    op.drop_table('call_events')
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index('ix_import_rows_import_status')
        batch_op.drop_index('ix_import_rows_import_row')

    op.drop_table('import_rows')
    with op.batch_alter_table('contact_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_assignments_employee_status')
        batch_op.drop_index('ix_contact_assignments_contact')
        batch_op.drop_index('ix_contact_assignments_campaign')

    op.drop_table('contact_assignments')
    with op.batch_alter_table('campaign_contacts', schema=None) as batch_op:
        batch_op.drop_index('ix_campaign_contacts_contact')
        batch_op.drop_index('ix_campaign_contacts_campaign_status')

    op.drop_table('campaign_contacts')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index('ix_calls_status_started')
        batch_op.drop_index('ix_calls_employee_started')
        batch_op.drop_index('ix_calls_contact_started')
        batch_op.drop_index('ix_calls_campaign_started')

    op.drop_table('calls')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('ix_contacts_status')
        batch_op.drop_index('ix_contacts_next_eligible_at')
        batch_op.drop_index('ix_contacts_category')

    op.drop_table('contacts')
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_index('ix_imports_created_by_created')

    op.drop_table('imports')
    with op.batch_alter_table('employee_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_sessions_employee_revoked')

    op.drop_table('employee_sessions')
    op.drop_table('campaign_assignees')
    op.drop_table('settings')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_employee_read_created')

    op.drop_table('notifications')
    op.drop_table('employee_devices')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_status')

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_actor_created')
        batch_op.drop_index('ix_audit_logs_action_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('ix_employees_team_active')

    op.drop_table('employees')
    op.drop_table('teams')
    op.drop_table('roles')
    op.drop_table('call_dispositions')
    # ### end Alembic commands ###
